language: node_js
node_js:
 - "node"
install:
 - npm install -g firebase-tools
script:
 - npm test
deploy:
  provider: firebase
  on:
   branch: master
  token:
    secure: FIREBASE_TOKEN
  message: "Deploying to Firebase"
